// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC5aWDtuvPJ-1Inq8b3dquwUyPZs-JPTI',
    appId: '1:627781265017:web:390acb3c02e939f04f96a8',
    messagingSenderId: '627781265017',
    projectId: 'notifaction-a5d3b',
    authDomain: 'notifaction-a5d3b.firebaseapp.com',
    storageBucket: 'notifaction-a5d3b.firebasestorage.app',
    measurementId: 'G-0WXD7GXX7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_TaUTwY-HzMYASyy5fkKos_IH5CcDeXM',
    appId: '1:627781265017:android:d37933ce96ab19de4f96a8',
    messagingSenderId: '627781265017',
    projectId: 'notifaction-a5d3b',
    storageBucket: 'notifaction-a5d3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMvmY_SgEINimBWukrWv_HhqELgH9JCrI',
    appId: '1:627781265017:ios:37178ef4a504b65c4f96a8',
    messagingSenderId: '627781265017',
    projectId: 'notifaction-a5d3b',
    storageBucket: 'notifaction-a5d3b.firebasestorage.app',
    iosBundleId: 'com.example.flutterAdvanced',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMvmY_SgEINimBWukrWv_HhqELgH9JCrI',
    appId: '1:627781265017:ios:37178ef4a504b65c4f96a8',
    messagingSenderId: '627781265017',
    projectId: 'notifaction-a5d3b',
    storageBucket: 'notifaction-a5d3b.firebasestorage.app',
    iosBundleId: 'com.example.flutterAdvanced',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC5aWDtuvPJ-1Inq8b3dquwUyPZs-JPTI',
    appId: '1:627781265017:web:e6962ad6d9531e474f96a8',
    messagingSenderId: '627781265017',
    projectId: 'notifaction-a5d3b',
    authDomain: 'notifaction-a5d3b.firebaseapp.com',
    storageBucket: 'notifaction-a5d3b.firebasestorage.app',
    measurementId: 'G-B85B5Q7M59',
  );
}
