default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distrubtion do
    sh "cd .. && flutter clean"
    sh "cd .. && flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:627781265017:android:d37933ce96ab19de4f96a8",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
  
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "nadersam33r@gmail.com",
      release_notes: "This is a new release of the app. Please test it and provide feedback."
    )
  end
end